// src/main/webapp/app/entities/sensor/update/sensor-update.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import SharedModule from 'app/shared/shared.module';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

import { ICliente } from 'app/entities/cliente/cliente.model';
import { ClienteService } from 'app/entities/cliente/service/cliente.service';
import { IDadoSensor } from 'app/entities/dado-sensor/dado-sensor.model';
import { DadoSensorService } from 'app/entities/dado-sensor/service/dado-sensor.service';
import { TipoSensor } from 'app/entities/enumerations/tipo-sensor.model';
import { SensorService } from '../service/sensor.service';
import { ISensor } from '../sensor.model';
import { SensorFormService, SensorFormGroup } from './sensor-form.service';

@Component({
  standalone: true,
  selector: 'jhi-sensor-update',
  templateUrl: './sensor-update.component.html',
  imports: [SharedModule, FormsModule, ReactiveFormsModule],
})
export class SensorUpdateComponent implements OnInit {
  isSaving = false;
  sensor: ISensor | null = null;
  tipoSensorValues = Object.keys(TipoSensor);

  clientesSharedCollection: ICliente[] = [];
  dadoSensorsSharedCollection: IDadoSensor[] = [];

  protected sensorService = inject(SensorService);
  protected sensorFormService = inject(SensorFormService);
  protected clienteService = inject(ClienteService);
  protected dadoSensorService = inject(DadoSensorService);
  protected activatedRoute = inject(ActivatedRoute);

  // eslint-disable-next-line @typescript-eslint/member-ordering
  editForm: SensorFormGroup = this.sensorFormService.createSensorFormGroup();

  compareCliente = (o1: ICliente | null, o2: ICliente | null): boolean => this.clienteService.compareCliente(o1, o2);

  compareDadoSensor = (o1: IDadoSensor | null, o2: IDadoSensor | null): boolean => this.dadoSensorService.compareDadoSensor(o1, o2);

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ sensor }) => {
      this.sensor = sensor;
      if (sensor) {
        this.updateForm(sensor);
      }

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const sensor = this.sensorFormService.getSensor(this.editForm);
    if (sensor.id !== null) {
      this.subscribeToSaveResponse(this.sensorService.update(sensor));
    } else {
      this.subscribeToSaveResponse(this.sensorService.create(sensor));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ISensor>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe({
      next: () => this.onSaveSuccess(),
      error: () => this.onSaveError(),
    });
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(sensor: ISensor): void {
    this.sensor = sensor;
    this.sensorFormService.resetForm(this.editForm, sensor);

    this.clientesSharedCollection = this.clienteService.addClienteToCollectionIfMissing<ICliente>(
      this.clientesSharedCollection,
      sensor.cliente,
    );
    this.dadoSensorsSharedCollection = this.dadoSensorService.addDadoSensorToCollectionIfMissing<IDadoSensor>(
      this.dadoSensorsSharedCollection,
      sensor.dadoSensores,
    );
  }

  protected loadRelationshipsOptions(): void {
    this.clienteService
      .query()
      .pipe(map((res: HttpResponse<ICliente[]>) => res.body ?? []))
      .pipe(map((clientes: ICliente[]) => this.clienteService.addClienteToCollectionIfMissing<ICliente>(clientes, this.sensor?.cliente)))
      .subscribe((clientes: ICliente[]) => (this.clientesSharedCollection = clientes));

    this.dadoSensorService
      .query()
      .pipe(map((res: HttpResponse<IDadoSensor[]>) => res.body ?? []))
      .pipe(
        map((dadoSensors: IDadoSensor[]) =>
          this.dadoSensorService.addDadoSensorToCollectionIfMissing<IDadoSensor>(dadoSensors, this.sensor?.dadoSensores),
        ),
      )
      .subscribe((dadoSensors: IDadoSensor[]) => (this.dadoSensorsSharedCollection = dadoSensors));
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <form name="editForm" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-sensor-heading" data-cy="SensorCreateUpdateHeading" jhiTranslate="smartIoTApp.sensor.home.createOrEditLabel">
        Create or edit a Sensor
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        @if (editForm.controls.id.value !== null) {
          <div class="mb-3">
            <label class="form-label" for="field_id" jhiTranslate="smartIoTApp.sensor.id">ID</label>
            <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
          </div>
        }

        <div class="mb-3">
          <label class="form-label" for="field_nome" jhiTranslate="smartIoTApp.sensor.nome">Nome</label>
          <input type="text" class="form-control" name="nome" id="field_nome" data-cy="nome" formControlName="nome" />
          @if (editForm.get('nome')!.invalid && (editForm.get('nome')!.dirty || editForm.get('nome')!.touched)) {
            <div>
              @if (editForm.get('nome')?.errors?.required) {
                <small class="form-text text-danger" jhiTranslate="entity.validation.required">This field is required.</small>
              }
              @if (editForm.get('nome')?.errors?.maxlength) {
                <small class="form-text text-danger" jhiTranslate="entity.validation.maxlength" [translateValues]="{ max: '100' }"
                  >This field cannot be longer than 100 characters.</small
                >
              }
            </div>
          }
        </div>

        <div class="mb-3">
          <label class="form-label" for="field_tipo" jhiTranslate="smartIoTApp.sensor.tipo">Tipo</label>
          <select class="form-control" name="tipo" formControlName="tipo" id="field_tipo" data-cy="tipo">
            <option [ngValue]="null">{{ 'smartIoTApp.TipoSensor.null' | translate }}</option>
            @for (tipoSensor of tipoSensorValues; track $index) {
              <option [value]="tipoSensor">{{ 'smartIoTApp.TipoSensor.' + tipoSensor | translate }}</option>
            }
          </select>
          @if (editForm.get('tipo')!.invalid && (editForm.get('tipo')!.dirty || editForm.get('tipo')!.touched)) {
            <div>
              @if (editForm.get('tipo')?.errors?.required) {
                <small class="form-text text-danger" jhiTranslate="entity.validation.required">This field is required.</small>
              }
            </div>
          }
        </div>

        <div class="mb-3">
          <label class="form-label" for="field_configuracao" jhiTranslate="smartIoTApp.sensor.configuracao">Configuracao</label>
          <input
            type="text"
            class="form-control"
            name="configuracao"
            id="field_configuracao"
            data-cy="configuracao"
            formControlName="configuracao"
          />
        </div>

        <div class="mb-3">
          <label class="form-label" for="field_cliente" jhiTranslate="smartIoTApp.sensor.cliente">Cliente</label>
          <select
            class="form-control"
            id="field_cliente"
            data-cy="cliente"
            name="cliente"
            formControlName="cliente"
            [compareWith]="compareCliente"
          >
            @if (editForm.get(['cliente'])!.value == null) {
              <option [ngValue]="null" selected></option>
            }
            @for (clienteOption of clientesSharedCollection; track $index) {
              <option [ngValue]="clienteOption">{{ clienteOption.nome }}</option>
            }
          </select>
        </div>
        @if (editForm.get(['cliente'])!.invalid && (editForm.get(['cliente'])!.dirty || editForm.get(['cliente'])!.touched)) {
          <div>
            @if (editForm.get(['cliente'])?.errors?.required) {
              <small class="form-text text-danger" jhiTranslate="entity.validation.required">This field is required.</small>
            }
          </div>
        }

        <div class="mb-3">
          <label class="form-label" for="field_dadoSensores" jhiTranslate="smartIoTApp.sensor.dadoSensores">Dado Sensores</label>
          <select
            class="form-control"
            id="field_dadoSensores"
            data-cy="dadoSensores"
            name="dadoSensores"
            formControlName="dadoSensores"
            [compareWith]="compareDadoSensor"
          >
            <option [ngValue]="null"></option>
            @for (dadoSensorOption of dadoSensorsSharedCollection; track $index) {
              <option [ngValue]="dadoSensorOption">{{ dadoSensorOption.timestamp }}</option>
            }
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>

// src/main/webapp/app/entities/sensor/sensor-update.tsx
import React, { useState, useEffect } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Button, Row, Col, FormText } from 'reactstrap';
import { isNumber, Translate, translate, ValidatedField, ValidatedForm } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { ICliente } from 'app/shared/model/cliente.model';
import { getEntities as getClientes } from 'app/entities/cliente/cliente.reducer';
import { IDadoSensor } from 'app/shared/model/dado-sensor.model';
import { getEntities as getDadoSensors } from 'app/entities/dado-sensor/dado-sensor.reducer';
import { ISensor } from 'app/shared/model/sensor.model';
import { TipoSensor } from 'app/shared/model/enumerations/tipo-sensor.model';
import { getEntity, updateEntity, createEntity, reset } from './sensor.reducer';

export const SensorUpdate = () => {
  const dispatch = useAppDispatch();

  const navigate = useNavigate();

  const { id } = useParams<'id'>();
  const isNew = id === undefined;

  const clientes = useAppSelector(state => state.cliente.entities);
  const dadoSensors = useAppSelector(state => state.dadoSensor.entities);
  const sensorEntity = useAppSelector(state => state.sensor.entity);
  const loading = useAppSelector(state => state.sensor.loading);
  const updating = useAppSelector(state => state.sensor.updating);
  const updateSuccess = useAppSelector(state => state.sensor.updateSuccess);
  const tipoSensorValues = Object.keys(TipoSensor);

  const handleClose = () => {
    navigate('/sensor' + location.search);
  };

  useEffect(() => {
    if (isNew) {
      dispatch(reset());
    } else {
      dispatch(getEntity(id));
    }

    dispatch(getClientes({}));
    dispatch(getDadoSensors({}));
  }, []);

  useEffect(() => {
    if (updateSuccess) {
      handleClose();
    }
  }, [updateSuccess]);

  // eslint-disable-next-line complexity
  const saveEntity = values => {
    if (values.id !== undefined && typeof values.id !== 'number') {
      values.id = Number(values.id);
    }

    const entity = {
      ...sensorEntity,
      ...values,
      cliente: clientes.find(it => it.id.toString() === values.cliente?.toString()),
      dadoSensores: dadoSensors.find(it => it.id.toString() === values.dadoSensores?.toString()),
    };

    if (isNew) {
      dispatch(createEntity(entity));
    } else {
      dispatch(updateEntity(entity));
    }
  };

  const defaultValues = () =>
    isNew
      ? {}
      : {
          tipo: 'TEMPERATURE',
          ...sensorEntity,
          cliente: sensorEntity?.cliente?.id,
          dadoSensores: sensorEntity?.dadoSensores?.id,
        };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="feedback360App.sensor.home.createOrEditLabel" data-cy="SensorCreateUpdateHeading">
            <Translate contentKey="feedback360App.sensor.home.createOrEditLabel">Create or edit a Sensor</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <ValidatedForm defaultValues={defaultValues()} onSubmit={saveEntity}>
              {!isNew ? (
                <ValidatedField
                  name="id"
                  required
                  readOnly
                  id="sensor-id"
                  label={translate('global.field.id')}
                  validate={{ required: true }}
                />
              ) : null}
              <ValidatedField
                label={translate('feedback360App.sensor.nome')}
                id="sensor-nome"
                name="nome"
                data-cy="nome"
                type="text"
                validate={{
                  required: { value: true, message: translate('entity.validation.required') },
                  maxLength: { value: 100, message: translate('entity.validation.maxlength', { max: 100 }) },
                }}
              />
              <ValidatedField label={translate('feedback360App.sensor.tipo')} id="sensor-tipo" name="tipo" data-cy="tipo" type="select">
                {tipoSensorValues.map(tipoSensor => (
                  <option value={tipoSensor} key={tipoSensor}>
                    {translate('feedback360App.TipoSensor.' + tipoSensor)}
                  </option>
                ))}
              </ValidatedField>
              <ValidatedField
                label={translate('feedback360App.sensor.configuracao')}
                id="sensor-configuracao"
                name="configuracao"
                data-cy="configuracao"
                type="text"
              />
              <ValidatedField
                id="sensor-cliente"
                name="cliente"
                data-cy="cliente"
                label={translate('feedback360App.sensor.cliente')}
                type="select"
                required
              >
                <option value="" key="0" />
                {clientes
                  ? clientes.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.nome}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <FormText>
                <Translate contentKey="entity.validation.required">This field is required.</Translate>
              </FormText>
              <ValidatedField
                id="sensor-dadoSensores"
                name="dadoSensores"
                data-cy="dadoSensores"
                label={translate('feedback360App.sensor.dadoSensores')}
                type="select"
              >
                <option value="" key="0" />
                {dadoSensors
                  ? dadoSensors.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.timestamp}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <Button tag={Link} id="cancel-save" data-cy="entityCreateCancelButton" to="/sensor" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </ValidatedForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

export default SensorUpdate;
