// src/main/webapp/app/entities/dado-sensor/delete/dado-sensor-delete-dialog.component.ts
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';

import SharedModule from 'app/shared/shared.module';
import { ITEM_DELETED_EVENT } from 'app/config/navigation.constants';
import { IDadoSensor } from '../dado-sensor.model';
import { DadoSensorService } from '../service/dado-sensor.service';

@Component({
  standalone: true,
  templateUrl: './dado-sensor-delete-dialog.component.html',
  imports: [SharedModule, FormsModule],
})
export class DadoSensorDeleteDialogComponent {
  dadoSensor?: IDadoSensor;

  protected dadoSensorService = inject(DadoSensorService);
  protected activeModal = inject(NgbActiveModal);

  cancel(): void {
    this.activeModal.dismiss();
  }

  confirmDelete(id: number): void {
    this.dadoSensorService.delete(id).subscribe(() => {
      this.activeModal.close(ITEM_DELETED_EVENT);
    });
  }
}

@if (dadoSensor) {
  <form name="deleteForm" (ngSubmit)="confirmDelete(dadoSensor.id!)">
    <div class="modal-header">
      <h4 class="modal-title" data-cy="dadoSensorDeleteDialogHeading" jhiTranslate="entity.delete.title">Confirm delete operation</h4>

      <span class="btn btn-close" data-dismiss="modal" aria-hidden="true" (click)="cancel()"></span>
    </div>

    <div class="modal-body">
      <jhi-alert-error></jhi-alert-error>
      <p id="jhi-delete-dadoSensor-heading" jhiTranslate="smartIoTApp.dadoSensor.delete.question" [translateValues]="{ id: dadoSensor.id }">
        Are you sure you want to delete Dado Sensor {{ dadoSensor.id }}?
      </p>
    </div>

    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-dismiss="modal" (click)="cancel()">
        <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
      </button>

      <button id="jhi-confirm-delete-dadoSensor" data-cy="entityConfirmDeleteButton" type="submit" class="btn btn-danger">
        <fa-icon icon="times"></fa-icon>&nbsp;<span jhiTranslate="entity.action.delete">Delete</span>
      </button>
    </div>
  </form>
}

// src/main/webapp/app/entities/dado-sensor/dado-sensor-delete-dialog.tsx
import React, { useEffect, useState } from 'react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { Modal, ModalHeader, ModalBody, ModalFooter, Button } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';
import { getEntity, deleteEntity } from './dado-sensor.reducer';

export const DadoSensorDeleteDialog = () => {
  const dispatch = useAppDispatch();

  const pageLocation = useLocation();
  const navigate = useNavigate();
  const { id } = useParams<'id'>();

  const [loadModal, setLoadModal] = useState(false);

  useEffect(() => {
    dispatch(getEntity(id));
    setLoadModal(true);
  }, []);

  const dadoSensorEntity = useAppSelector(state => state.dadoSensor.entity);
  const updateSuccess = useAppSelector(state => state.dadoSensor.updateSuccess);

  const handleClose = () => {
    navigate('/dado-sensor' + pageLocation.search);
  };

  useEffect(() => {
    if (updateSuccess && loadModal) {
      handleClose();
      setLoadModal(false);
    }
  }, [updateSuccess]);

  const confirmDelete = () => {
    dispatch(deleteEntity(dadoSensorEntity.id));
  };

  return (
    <Modal isOpen toggle={handleClose}>
      <ModalHeader toggle={handleClose} data-cy="dadoSensorDeleteDialogHeading">
        <Translate contentKey="entity.delete.title">Confirm delete operation</Translate>
      </ModalHeader>
      <ModalBody id="feedback360App.dadoSensor.delete.question">
        <Translate contentKey="feedback360App.dadoSensor.delete.question" interpolate={{ id: dadoSensorEntity.id }}>
          Are you sure you want to delete this DadoSensor?
        </Translate>
      </ModalBody>
      <ModalFooter>
        <Button color="secondary" onClick={handleClose}>
          <FontAwesomeIcon icon="ban" />
          &nbsp;
          <Translate contentKey="entity.action.cancel">Cancel</Translate>
        </Button>
        <Button id="jhi-confirm-delete-dadoSensor" data-cy="entityConfirmDeleteButton" color="danger" onClick={confirmDelete}>
          <FontAwesomeIcon icon="trash" />
          &nbsp;
          <Translate contentKey="entity.action.delete">Delete</Translate>
        </Button>
      </ModalFooter>
    </Modal>
  );
};

export default DadoSensorDeleteDialog;
