// src/main/webapp/app/entities/dado-sensor/detail/dado-sensor-detail.component.ts
import { Component, input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe } from 'app/shared/date';
import { IDadoSensor } from '../dado-sensor.model';

@Component({
  standalone: true,
  selector: 'jhi-dado-sensor-detail',
  templateUrl: './dado-sensor-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class DadoSensorDetailComponent {
  dadoSensor = input<IDadoSensor | null>(null);

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (dadoSensor()) {
      <div>
        <h2 data-cy="dadoSensorDetailsHeading"><span jhiTranslate="smartIoTApp.dadoSensor.detail.title">Dado Sensor</span></h2>

        <hr />

        <jhi-alert-error></jhi-alert-error>

        <jhi-alert></jhi-alert>

        <dl class="row-md jh-entity-details">
          <dt><span jhiTranslate="global.field.id">ID</span></dt>
          <dd>
            <span>{{ dadoSensor()!.id }}</span>
          </dd>
          <dt><span jhiTranslate="smartIoTApp.dadoSensor.dados">Dados</span></dt>
          <dd>
            <span>{{ dadoSensor()!.dados }}</span>
          </dd>
          <dt><span jhiTranslate="smartIoTApp.dadoSensor.timestamp">Timestamp</span></dt>
          <dd>
            <span>{{ dadoSensor()!.timestamp | formatMediumDatetime }}</span>
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
        </button>

        <button type="button" [routerLink]="['/dado-sensor', dadoSensor()!.id, 'edit']" class="btn btn-primary">
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
        </button>
      </div>
    }
  </div>
</div>

// src/main/webapp/app/entities/dado-sensor/dado-sensor-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './dado-sensor.reducer';

export const DadoSensorDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const dadoSensorEntity = useAppSelector(state => state.dadoSensor.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="dadoSensorDetailsHeading">
          <Translate contentKey="feedback360App.dadoSensor.detail.title">DadoSensor</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{dadoSensorEntity.id}</dd>
          <dt>
            <span id="dados">
              <Translate contentKey="feedback360App.dadoSensor.dados">Dados</Translate>
            </span>
          </dt>
          <dd>{dadoSensorEntity.dados}</dd>
          <dt>
            <span id="timestamp">
              <Translate contentKey="feedback360App.dadoSensor.timestamp">Timestamp</Translate>
            </span>
          </dt>
          <dd>
            {dadoSensorEntity.timestamp ? <TextFormat value={dadoSensorEntity.timestamp} type="date" format={APP_DATE_FORMAT} /> : null}
          </dd>
        </dl>
        <Button tag={Link} to="/dado-sensor" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/dado-sensor/${dadoSensorEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default DadoSensorDetail;
