// src/main/webapp/app/entities/sensor/sensor-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './sensor.reducer';

export const SensorDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const sensorEntity = useAppSelector(state => state.sensor.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="sensorDetailsHeading">
          <Translate contentKey="feedback360App.sensor.detail.title">Sensor</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{sensorEntity.id}</dd>
          <dt>
            <span id="nome">
              <Translate contentKey="feedback360App.sensor.nome">Nome</Translate>
            </span>
          </dt>
          <dd>{sensorEntity.nome}</dd>
          <dt>
            <span id="tipo">
              <Translate contentKey="feedback360App.sensor.tipo">Tipo</Translate>
            </span>
          </dt>
          <dd>{sensorEntity.tipo}</dd>
          <dt>
            <span id="configuracao">
              <Translate contentKey="feedback360App.sensor.configuracao">Configuracao</Translate>
            </span>
          </dt>
          <dd>{sensorEntity.configuracao}</dd>
          <dt>
            <Translate contentKey="feedback360App.sensor.cliente">Cliente</Translate>
          </dt>
          <dd>{sensorEntity.cliente ? sensorEntity.cliente.nome : ''}</dd>
          <dt>
            <Translate contentKey="feedback360App.sensor.dadoSensores">Dado Sensores</Translate>
          </dt>
          <dd>{sensorEntity.dadoSensores ? sensorEntity.dadoSensores.timestamp : ''}</dd>
        </dl>
        <Button tag={Link} to="/sensor" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/sensor/${sensorEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default SensorDetail;

// src/main/webapp/app/entities/sensor/detail/sensor-detail.component.ts
import { Component, input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe } from 'app/shared/date';
import { ISensor } from '../sensor.model';

@Component({
  standalone: true,
  selector: 'jhi-sensor-detail',
  templateUrl: './sensor-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class SensorDetailComponent {
  sensor = input<ISensor | null>(null);

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (sensor()) {
      <div>
        <h2 data-cy="sensorDetailsHeading"><span jhiTranslate="smartIoTApp.sensor.detail.title">Sensor</span></h2>

        <hr />

        <jhi-alert-error></jhi-alert-error>

        <jhi-alert></jhi-alert>

        <dl class="row-md jh-entity-details">
          <dt><span jhiTranslate="global.field.id">ID</span></dt>
          <dd>
            <span>{{ sensor()!.id }}</span>
          </dd>
          <dt><span jhiTranslate="smartIoTApp.sensor.nome">Nome</span></dt>
          <dd>
            <span>{{ sensor()!.nome }}</span>
          </dd>
          <dt><span jhiTranslate="smartIoTApp.sensor.tipo">Tipo</span></dt>
          <dd>
            <span [jhiTranslate]="'smartIoTApp.TipoSensor.' + (sensor()!.tipo ?? 'null')">{{
              { null: '', TEMPERATURE: 'TEMPERATURE', HUMIDITY: 'HUMIDITY', PRESSURE: 'PRESSURE' }[sensor()!.tipo ?? 'null']
            }}</span>
          </dd>
          <dt><span jhiTranslate="smartIoTApp.sensor.configuracao">Configuracao</span></dt>
          <dd>
            <span>{{ sensor()!.configuracao }}</span>
          </dd>
          <dt><span jhiTranslate="smartIoTApp.sensor.configuracaoAlertas">Configuracao Alertas</span></dt>
          <dd>
            @if (sensor()!.configuracaoAlertas) {
              <div>
                <a [routerLink]="['/configuracao-alerta', sensor()!.configuracaoAlertas?.id, 'view']">{{
                  sensor()!.configuracaoAlertas?.id
                }}</a>
              </div>
            }
          </dd>
          <dt><span jhiTranslate="smartIoTApp.sensor.dadoSensores">Dado Sensores</span></dt>
          <dd>
            @if (sensor()!.dadoSensores) {
              <div>
                <a [routerLink]="['/dado-sensor', sensor()!.dadoSensores?.id, 'view']">{{ sensor()!.dadoSensores?.id }}</a>
              </div>
            }
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
        </button>

        <button type="button" [routerLink]="['/sensor', sensor()!.id, 'edit']" class="btn btn-primary">
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
        </button>
      </div>
    }
  </div>
</div>
