// src/main/webapp/app/entities/configuracao-alerta/configuracao-alerta-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './configuracao-alerta.reducer';

export const ConfiguracaoAlertaDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const configuracaoAlertaEntity = useAppSelector(state => state.configuracaoAlerta.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="configuracaoAlertaDetailsHeading">
          <Translate contentKey="feedback360App.configuracaoAlerta.detail.title">ConfiguracaoAlerta</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{configuracaoAlertaEntity.id}</dd>
          <dt>
            <span id="limite">
              <Translate contentKey="feedback360App.configuracaoAlerta.limite">Limite</Translate>
            </span>
          </dt>
          <dd>{configuracaoAlertaEntity.limite}</dd>
          <dt>
            <span id="email">
              <Translate contentKey="feedback360App.configuracaoAlerta.email">Email</Translate>
            </span>
          </dt>
          <dd>{configuracaoAlertaEntity.email}</dd>
          <dt>
            <Translate contentKey="feedback360App.configuracaoAlerta.sensor">Sensor</Translate>
          </dt>
          <dd>{configuracaoAlertaEntity.sensor ? configuracaoAlertaEntity.sensor.nome : ''}</dd>
        </dl>
        <Button tag={Link} to="/configuracao-alerta" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/configuracao-alerta/${configuracaoAlertaEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default ConfiguracaoAlertaDetail;

// src/main/webapp/app/entities/configuracao-alerta/detail/configuracao-alerta-detail.component.ts
import { Component, input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe } from 'app/shared/date';
import { IConfiguracaoAlerta } from '../configuracao-alerta.model';

@Component({
  standalone: true,
  selector: 'jhi-configuracao-alerta-detail',
  templateUrl: './configuracao-alerta-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class ConfiguracaoAlertaDetailComponent {
  configuracaoAlerta = input<IConfiguracaoAlerta | null>(null);

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (configuracaoAlerta()) {
      <div>
        <h2 data-cy="configuracaoAlertaDetailsHeading">
          <span jhiTranslate="smartIoTApp.configuracaoAlerta.detail.title">Configuracao Alerta</span>
        </h2>

        <hr />

        <jhi-alert-error></jhi-alert-error>

        <jhi-alert></jhi-alert>

        <dl class="row-md jh-entity-details">
          <dt><span jhiTranslate="global.field.id">ID</span></dt>
          <dd>
            <span>{{ configuracaoAlerta()!.id }}</span>
          </dd>
          <dt><span jhiTranslate="smartIoTApp.configuracaoAlerta.limite">Limite</span></dt>
          <dd>
            <span>{{ configuracaoAlerta()!.limite }}</span>
          </dd>
          <dt><span jhiTranslate="smartIoTApp.configuracaoAlerta.email">Email</span></dt>
          <dd>
            <span>{{ configuracaoAlerta()!.email }}</span>
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
        </button>

        <button type="button" [routerLink]="['/configuracao-alerta', configuracaoAlerta()!.id, 'edit']" class="btn btn-primary">
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
        </button>
      </div>
    }
  </div>
</div>
