// src/main/webapp/app/entities/configuracao-alerta/configuracao-alerta-delete-dialog.tsx
import React, { useEffect, useState } from 'react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { Modal, ModalHeader, ModalBody, ModalFooter, Button } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';
import { getEntity, deleteEntity } from './configuracao-alerta.reducer';

export const ConfiguracaoAlertaDeleteDialog = () => {
  const dispatch = useAppDispatch();

  const pageLocation = useLocation();
  const navigate = useNavigate();
  const { id } = useParams<'id'>();

  const [loadModal, setLoadModal] = useState(false);

  useEffect(() => {
    dispatch(getEntity(id));
    setLoadModal(true);
  }, []);

  const configuracaoAlertaEntity = useAppSelector(state => state.configuracaoAlerta.entity);
  const updateSuccess = useAppSelector(state => state.configuracaoAlerta.updateSuccess);

  const handleClose = () => {
    navigate('/configuracao-alerta' + pageLocation.search);
  };

  useEffect(() => {
    if (updateSuccess && loadModal) {
      handleClose();
      setLoadModal(false);
    }
  }, [updateSuccess]);

  const confirmDelete = () => {
    dispatch(deleteEntity(configuracaoAlertaEntity.id));
  };

  return (
    <Modal isOpen toggle={handleClose}>
      <ModalHeader toggle={handleClose} data-cy="configuracaoAlertaDeleteDialogHeading">
        <Translate contentKey="entity.delete.title">Confirm delete operation</Translate>
      </ModalHeader>
      <ModalBody id="feedback360App.configuracaoAlerta.delete.question">
        <Translate contentKey="feedback360App.configuracaoAlerta.delete.question" interpolate={{ id: configuracaoAlertaEntity.id }}>
          Are you sure you want to delete this ConfiguracaoAlerta?
        </Translate>
      </ModalBody>
      <ModalFooter>
        <Button color="secondary" onClick={handleClose}>
          <FontAwesomeIcon icon="ban" />
          &nbsp;
          <Translate contentKey="entity.action.cancel">Cancel</Translate>
        </Button>
        <Button id="jhi-confirm-delete-configuracaoAlerta" data-cy="entityConfirmDeleteButton" color="danger" onClick={confirmDelete}>
          <FontAwesomeIcon icon="trash" />
          &nbsp;
          <Translate contentKey="entity.action.delete">Delete</Translate>
        </Button>
      </ModalFooter>
    </Modal>
  );
};

export default ConfiguracaoAlertaDeleteDialog;

// src/main/webapp/app/entities/configuracao-alerta/delete/configuracao-alerta-delete-dialog.component.ts
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';

import SharedModule from 'app/shared/shared.module';
import { ITEM_DELETED_EVENT } from 'app/config/navigation.constants';
import { IConfiguracaoAlerta } from '../configuracao-alerta.model';
import { ConfiguracaoAlertaService } from '../service/configuracao-alerta.service';

@Component({
  standalone: true,
  templateUrl: './configuracao-alerta-delete-dialog.component.html',
  imports: [SharedModule, FormsModule],
})
export class ConfiguracaoAlertaDeleteDialogComponent {
  configuracaoAlerta?: IConfiguracaoAlerta;

  protected configuracaoAlertaService = inject(ConfiguracaoAlertaService);
  protected activeModal = inject(NgbActiveModal);

  cancel(): void {
    this.activeModal.dismiss();
  }

  confirmDelete(id: number): void {
    this.configuracaoAlertaService.delete(id).subscribe(() => {
      this.activeModal.close(ITEM_DELETED_EVENT);
    });
  }
}

@if (configuracaoAlerta) {
  <form name="deleteForm" (ngSubmit)="confirmDelete(configuracaoAlerta.id!)">
    <div class="modal-header">
      <h4 class="modal-title" data-cy="configuracaoAlertaDeleteDialogHeading" jhiTranslate="entity.delete.title">
        Confirm delete operation
      </h4>

      <span class="btn btn-close" data-dismiss="modal" aria-hidden="true" (click)="cancel()"></span>
    </div>

    <div class="modal-body">
      <jhi-alert-error></jhi-alert-error>
      <p
        id="jhi-delete-configuracaoAlerta-heading"
        jhiTranslate="smartIoTApp.configuracaoAlerta.delete.question"
        [translateValues]="{ id: configuracaoAlerta.id }"
      >
        Are you sure you want to delete Configuracao Alerta {{ configuracaoAlerta.id }}?
      </p>
    </div>

    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-dismiss="modal" (click)="cancel()">
        <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
      </button>

      <button id="jhi-confirm-delete-configuracaoAlerta" data-cy="entityConfirmDeleteButton" type="submit" class="btn btn-danger">
        <fa-icon icon="times"></fa-icon>&nbsp;<span jhiTranslate="entity.action.delete">Delete</span>
      </button>
    </div>
  </form>
}
